hhru/api

docs_eng/employer_addresses.md
docs_eng/employer_departments.md
docs_eng/employer_managers.md
docs_eng/employer_tests.md
docs_eng/employer_vacancies.md
docs_eng/employer_vacancy_areas_active.md

Как оказалось саму публикацию я выложил на прошлом этапе, не хватало только справочников

english docs: add employer directories

---

docs_eng/README.md
docs_eng/address.md
docs_eng/areas.md
docs_eng/dictionaries.md
docs_eng/employer_dictionaries.md
docs_eng/employer_negotiations.md
docs_eng/employer_vacancies.md
docs_eng/employer_vacancies_for_invitation.md
docs_eng/employer_vacancy_branded_templates.md
docs_eng/employers.md
docs_eng/errors.md
docs_eng/manager_settings.md
docs_eng/me.md
docs_eng/negotiations.md
docs_eng/resumes.md
docs_eng/saved_search.md
docs_eng/vacancies.md

кроме clusters которых пока в переводе нет

обновление документации на английском

---

README.md
docs/resumes.md
docs_eng/resumes.md

https://jira.hh.ru/browse/HH-66778

Готовность резюме к публикации

---

docs/vacancies.md

https://jira.hh.ru/browse/HH-64083

add isBlacklisted to full vacancy

---

docs/vacancies.md
docs_eng/vacancies.md

https://jira.hh.ru/browse/HH-71311

добавили информацию о расстоянии до центра сортировки при поиске вакансий

---

docs/employer_negotiations.md
docs_eng/employer_negotiations.md

https://jira.hh.ru/browse/HH-76156

add collection description

---

docs/applicant_comments.md
docs/assessment.md
docs/employer_negotiations.md
docs/negotiation_message_templates.md
docs/resume_negotiations_history.md
docs/resumes.md

https://jira.hh.ru/browse/HH-79987

fix payed path

---

docs/salary_reports.md

https://jira.hh.ru/browse/HH-80210
Доку к новому параметру `extend_sources` https://github.com/hhru/hhapi/pull/942

HH-80210 Add param extend_sources for salary_evaluation

---

docs/errors.md

https://jira.hh.ru/browse/HH-81937

HH-81937 add reasons to errors

---

README.md
docs/FAQ.md

https://jira.hh.ru/browse/HH-83304

HH-83304 Добавила пример приглашения соискателя на собеседование

---

docs_eng/employers.md

Убрала упоминание о старом формате ошибки

remove old error format mention

---

docs/resumes.md
docs_eng/resumes.md

https://jira.hh.ru/browse/HH-88315
Необязательный факультет
api https://github.com/hhru/hhapi/pull/1056

HH-88315 make primary education organization nullable

---

docs/errors.md
docs_eng/errors.md

https://jira.hh.ru/browse/HH-89684
Добавил новые ошибки - `account is locked`, `password invalidated`, `login not verified`.
Дал описание и варианты, что должен делать пользователь.

Добавил новые ошибки при oauth авторизации и обновлении токенов

---

docs/employer_negotiations.md

https://jira.hh.ru/browse/HH-90194

Переименовано название сортировки в откликах работодателя

---

docs/employers.md
docs_eng/employers.md

добавили отрасль в выдачу компании

---

docs_eng/README.md
docs_eng/authorization_for_user.md
docs_eng/errors.md
docs_eng/manager_accounts.md
docs_eng/me.md

Перевод рабочих аккаунтов менеджера

add manager extra account

---

README.md
docs_eng/README.md

Метод доступен всем работодателя, а не только, тем у которых есть доступ к платным методам.

Исправлена пометка доступности метода работодателям

---

docs/hosts.md
docs_eng/hosts.md

https://jira.hh.ru/browse/HH-105162

HH-105162 Change jobs.day.az -> hh1.az

---

docs_eng/README.md
docs_eng/employer_vacancies.md

Possible options available to current manager for publishing of vacancies

---

docs/hosts.md
docs/resume_visibility.md
docs_eng/hosts.md
docs_eng/resume_visibility.md

https://jira.hh.ru/browse/HH-106451
Украина переезжает на новый домен

HH-106451 hh.ua -> grc.ua

---

docs/negotiations.md

https://jira.hh.ru/browse/HH-109763

HH-109763 filter->status

---

docs/hosts.md
docs_eng/hosts.md

https://jira.hh.ru/browse/HH-129196

Актуализировали адрес белорусского сайта

---

docs/languages.md
docs/locales.md

языки в OpenAPI

---

docs/vacancies.md
docs_eng/vacancies.md

https://jira.hh.ru/browse/HH-147265

HH-147265 add docs about multiple experiences in vacancy search

---

docs/employer_managers.md
docs_eng/employer_managers.md

перевод метода в openAPI

---

docs/areas.md
docs/hosts.md
docs/resume_visibility.md
docs_eng/areas.md
docs_eng/hosts.md
docs_eng/resume_visibility.md

актуализируем документацию

---

docs/vacancies.md

https://jira.hh.ru/browse/HH-162681

Удалены дубли в описании параметров к методу GET /vacancies

---

docs/role_catalog_article.md
docs_eng/role_catalog_article.md

https://jira.hh.ru/browse/HH-163057

Исправлена ссылка в role_catalog_article

---

README.md
docs_eng/README.md

https://jira.hh.ru/browse/HH-163359

Удалена дублирующая ссылка

---

docs/employer_vacancies.md
docs_eng/employer_vacancies.md

https://jira.hh.ru/browse/HH-164040

Removed field description

---

docs/vacancies.md
docs_eng/vacancies.md

Add target employer count example to vacancies.md

---

docs/employer_vacancies.md
docs_eng/employer_vacancies.md

https://jira.hh.ru/browse/HH-167628

HH-167628 Fixed link

---

docs/vacancies.md
docs_eng/vacancies.md

Calls counters were added to GET /vacacnies/{id}

---

README.md
docs/vacancies.md
docs_eng/README.md
docs_eng/vacancies.md

 fix openAPI links

---

docs/employer_vacancies.md
docs_eng/employer_vacancies.md

Информация о менеджере в списке опубликованных вакансий

Информация о менеджере в списке опубликованных вакансий

---

docs/employer_vacancies.md
docs_eng/employer_vacancies.md

Перевели удаление вакансий в OpenAPI

---

docs/employer_vacancies.md
docs_eng/employer_vacancies.md

Перевели архивные вакансии в OpenAPI

---

docs/employer_vacancies.md
docs_eng/employer_vacancies.md

HH-174356 add driver_license_types description

---

docs/employer_negotiations.md
docs_eng/employer_negotiations.md

https://jira.hh.ru/browse/HH-180487

Добавлено описание сгенерированных коллекций в откликах

---

docs/employer_negotiations.md
docs_eng/employer_negotiations.md

Переименованы поля в фильтрах откликов

Переименованы поля в фильтрах откликов

---

docs/employer_negotiations.md
docs_eng/employer_negotiations.md

Перенесли просмотр\изменение предпочитаемой сортировки откликов в OpenAPI

---

README.md
docs/errors.md
docs/resumes.md
docs/role_catalog_article.md
docs_eng/README.md
docs_eng/errors.md
docs_eng/resumes.md
docs_eng/role_catalog_article.md

Перевели создание, клонирование и удаление резюме в OpenAPI

---

docs/vacancies.md
docs_eng/vacancies.md

Заодно убрал поле `video_vacancy`, так как его нет в кратком представлении вакансии.

Добавление информации о брендировании вакансии и признака отображения лого в поисковой выдаче

---

docs/negotiations.md
docs_eng/negotiations.md

https://jira.hh.ru/browse/HH-187882

Метод скрытия активного отклика перенесен на openapi

---

docs/salary_dictionaries.md
docs_eng/salary_dictionaries.md

Перевели профобласти и специализации в OpenAPI

---

docs/authorization_for_user.md

 правка OpenAPI-ссылки
